name: Using run
on: [push]
env:
  START_VALUE: 1
  NEXT_VALUE_FILE: next_value.txt
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize the variable in a file with start_value == ${{ env.START_VALUE }}
      run: expr $START_VALUE + 10 | tee ${{ env.NEXT_VALUE_FILE }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NEXT_VALUE
        path: ${{ env.NEXT_VALUE_FILE }}
  
  second:
    runs-on: ubuntu-latest
    needs: [first]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: NEXT_VALUE
    - name: Show the workspace so you can see where the files are
      run: find .
    - name: Update the variable in a file
      run: |
        variable=$(cat ./NEXT_VALUE/${{ env.NEXT_VALUE_FILE }})
        expr $variable + 10 | tee ${{ env.NEXT_VALUE_FILE }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NEXT_VALUE
        path: ${{ env.NEXT_VALUE_FILE }}
  third:
    runs-on: ubuntu-latest
    needs: [second]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: NEXT_VALUE
    - name: Show the workspace so you can see where the files are
      run: find .
    - name: Update the variable in a file
      run: |
        variable=$(cat ./NEXT_VALUE/${{ env.NEXT_VALUE_FILE }})
        expr $variable + 10 | tee ${{ env.NEXT_VALUE_FILE }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NEXT_VALUE
        path: ${{ env.NEXT_VALUE_FILE }}
